name: showcase_cicd_snowflake

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: pip install snowflake-connector-python

      - name: Validate version strings
        run: python sid.py  # Replace with your actual script filename

      - name: Install schemachange
        run: pip install schemachange

      - name: Set up Environment Variables
        run: |
         echo "SF_ACCOUNT=${{ secrets.SF_ACCOUNT }}" >> $GITHUB_ENV
         echo "SF_USERNAME=${{ secrets.SF_USERNAME }}" >> $GITHUB_ENV
         echo "SF_ROLE=${{ secrets.SF_ROLE }}" >> $GITHUB_ENV
         echo "SF_WAREHOUSE=${{ secrets.SF_WAREHOUSE }}" >> $GITHUB_ENV
         echo "SF_DATABASE=${{ secrets.SF_DATABASE }}" >> $GITHUB_ENV
         echo "SNOWFLAKE_PASSWORD=${{ secrets.SF_PASSWORD }}" >> $GITHUB_ENV
        # Set other Snowflake environment variables as needed

      - name: Run Python Script
        run: |
         export SNOWFLAKE_PASSWORD
         
