name: Feature Branch CI/CD for Snowflake

on:
  pull_request:
    branches:
      - feature*

jobs:
  feature-branch-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Validate file names
        id: validate_files
        run: |
          python scripts/sid.py

      - name: Set output for validation
        if: steps.validate_files.outputs.valid == 'true' && success()
        run: echo "::set-output name=valid::true"
