name: showcase_cicd_snowflake

on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**'

workflow_dispatch:

jobs:
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Install schemachange
        run: |
          echo "Step 1: Installing schemachange"
          pip install --upgrade schemachange

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          
          # Filter and run schemachange for files matching the pattern
          for file in $GITHUB_WORKSPACE/dbscripts/[vV]*.[0-9]*.[0-9]*__[a-zA-Z0-9_]+.sql; do
            if [[ -f "$file" ]]; then
              echo "Processing file: $file"
              schemachange -f "$GITHUB_WORKSPACE/dbscripts" -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
            else
              echo "File not found: $file"
            fi
          done
